### ISSUE TITLE
Crash when adding recipes

### ISSUE THREAD

**Issue by Njet75** [QMXTech/MachineMusePowersuits#17]
Works fine without recipes.
crashes when added
Version ModularPowersuits-0.11.0.5-QMX

http://pastebin.com/uPQXBCBS

**Comment by Sunconure11** [comment]
I have the same exact error as you.

**Comment by Korynkai** [comment]
Great... That GSON/JSON bug is back... and you are using Numina-0.4.0.5-QMX?

**Comment by Sunconure11** [comment]
I am using the latest version of Numina and such for it.

**Comment by EzerArch** [comment]
Interesting that, in my case, MPS will crash if I add CustomNPCs mod. If I remove the *.recipe files the game won't crash with both mods installed. I reported the issue to Noppes (CustomNPCs developer) and he said it was MPS having problems with reading json files.

**Comment by Brycey92** [comment]
I get the same error with all latest files. http://pastebin.com/0zgb7mzC

**Comment by EzerArch** [comment]
@Brycey92, the fix for this bug is scheduled for the next release. See **Milestone** on the right.

**Comment by Korynkai** [comment]
Finally fixed internally. However I cannot release Numina 0.4.0.6-QMX until Jörg Haeger returns my email authorizing the relicensing of OggAudioData to LGPL.

**Comment by EzerArch** [comment]
Glad to hear the news!

**Comment by Brycey92** [comment]
Thanks for the fix!

**Comment by Korynkai** [comment]
EzerArch: Most definitely will not crash with CustomNPCs anymore.

However... https://github.com/Chicken-Bones/NotEnoughItems/issues/155 <-- hoping I can get @Chicken-Bones' assistance on this one, Numina's definitely involved but I cannot find its entry point anywhere, and I'm printing strings all over the place trying to find it, too.... :P

**Comment by Korynkai** [comment]
Fix released for the initial issue. Not only that, but we have progress on https://github.com/Chicken-Bones/NotEnoughItems/issues/155 apparently, I will return my gratitude once I finish up some things...
