### ISSUE TITLE
Thermal Expansion Recipes Out Of Date

### ISSUE THREAD

**Issue by TeliUmbrarum** [QMXTech/MachineMusePowersuits#19]
With the recipes installed in their folder I can't seem to build half the items from this mod do to the ingredients no longer existing in thermal expansion.

**Comment by Korynkai** [comment]
I'll look into this and ensure the recipe file is up to date.

**Comment by TeliUmbrarum** [comment]
Thanks!

**Comment by Korynkai** [comment]
Released and updated.
