### ISSUE TITLE
No configurable recipes

### ISSUE THREAD

**Issue by DrummingFish** [QMXTech/MachineMusePowersuits#24]
Before 1.7.* the mod included recipe sets that could be turned on and off through the config (GregTech, IndustrialCraft, Thermal Expansion, Universal Electricity (now Resonant Engine), and vanilla).

**Comment by Korynkai** [comment]
Assuming you already saw https://github.com/QMXTech/MachineMusePowersuits/issues/17 and https://github.com/QMXTech/MachineMusePowersuits/issues/19? 
Yeah, GregTech, IndustrialCraft2, ThermalExpansion and vanilla recipes will all be automatically placed and handled in 0.11.0.6-QMX depending on config settings and mod presence. Also I have planned support for EnderIO and Mekanism. Universal Electricity/Resonant Engine/Resonant Induction/Electrodynamics recipes will be reintroduced when @Calclavia gets it together and releases a (somewhat) stable build.

**Comment by DrummingFish** [comment]
That's great! I look forward to the update. I actually closed the issue as I was going to put it up on Bugzilla instead but if it's good here then great.

**Comment by Korynkai** [comment]
Yeah, I would've said under normal circumstances to put this in Bugzilla, but... Actually forgot one label that says it all.... ^_^

**Comment by Korynkai** [comment]
Released
