### ISSUE TITLE
Looking up Item usage in NEI crashes game.

### ISSUE THREAD

**Issue by Andre-Maartens** [QMXTech/MachineMusePowersuits#28]
https://www.dropbox.com/s/x4txx95i20qeb51/new%20%201.txt?dl=0
Word of advice: Start at the bottom :grin:

**Comment by Korynkai** [comment]
1: Trying to move things along to bugzilla, so if you wouldn't mind posting there from now on (https://bugzilla.qmxtech.com)? I do have an anonymous reports modification in place so reporters do not have to log in... I did post in #23 regarding this and mentioned the reason I still have this open...
2: Please see https://github.com/Chicken-Bones/NotEnoughItems/issues/155, this issue is not caused by PowerSuits or Numina's recipe handler itself.

**Comment by Korynkai** [comment]
In fact, should be fixed as of https://github.com/Chicken-Bones/NotEnoughItems/commit/d02fdc2f0bde3437c508ce9516e2a735fa24690d

**Comment by Chicken-Bones** [comment]
My apologies for wrong commit link (edited in original issue)

**Comment by Andre-Maartens** [comment]
Just tessted on the same instance just without numina and mps and u worked...
so it must be related to mps and or numina.

**Comment by Chicken-Bones** [comment]
Should have some warnings in the logs

**Comment by Andre-Maartens** [comment]
it keep crashing stating an error with screen event updating so i want to now if there is any workarounds besides disabling mods

**Comment by Chicken-Bones** [comment]
logs?

**Comment by Andre-Maartens** [comment]
will need to use dropbox tho because log is huge so i will paste the short cut out here and the full in dropbox. Will edit with links in a min.

**Comment by Andre-Maartens** [comment]
By the way it happens only when looking up the usage the recipe look up is fine
Can i workaround this using minetweaker?
Full log:
web view: https://www.dropbox.com/s/xpoztlrk4plhb0f/Crash.txt?dl=0
npp++ : https://www.dropbox.com/s/xpoztlrk4plhb0f/Crash.txt?dl=1

**Comment by Andre-Maartens** [comment]
I Disabled all forms of recipes of mps and now it works...?
So I assume MPS/Numina is screwing up recipe wise so i'll use minetweaker

**Comment by Korynkai** [comment]
Oy....
@Chicken-Bones I cannot seem to verify this issue is coming from within Numina... Can you verify anything on your end? NEI isn't trying to pull up the TinkerTable UI to get the usage recipe, is it? Can't think of what else it would be choking on unless... NEI isn't choking on nulls in CachedShapedRecipe, is it?

**Comment by Andre-Maartens** [comment]
i did notice that the recipes is trying to call for some thermal expansion blocks that has changed their unlocalized names

**Comment by Korynkai** [comment]
Interesting, so did that solve the issue? A related recipe ingredient naming issue was reported on MinecraftForums.net and I planned on releasing the patched .recipes files as a minor metafile update preceeding 0.11.0.8-QMX, which is why I ask.

**Comment by Andre-Maartens** [comment]
yea i delleted the recipes and set the config option to false and remade the most recipes the same using double door devs in game minetweaker so i will post a link to the recipe script

**Comment by Korynkai** [comment]
Did you test the new recipes using Numina's recipe handler as well? Or just MineTweaker? Numina will automatically load any .recipes files placed within the folder `config/machinemuse/recipes` as well (subdirectories are reserved for automatic recipes) however the syntax needs to be Numina's JSON shaped recipe syntax, not sure how this differs from MineTweaker's... Either way, once you post the script, I'll know.

**Comment by Andre-Maartens** [comment]
just minetweaker will test it tomorrow can you send me a example json recipe format?

**Comment by Korynkai** [comment]
Odd spacing at the bottom, not sure how that happened, but the best example would be any of the recipes files within Powersuits or MPSA, for instance: https://github.com/QMXTech/MachineMusePowersuits/blob/master/src/main/resources/assets/powersuits/recipes/vanilla.recipes
