### ISSUE TITLE
TODO: Enhance Jetpack speed

### ISSUE THREAD

**Issue by Korynkai** [QMXTech/MachineMusePowersuits#5]
Jetpack distance travelled seems rather slow... Todo: make this more comparable to SimplyJetpacks or Mekanism.

**Comment by Korynkai** [comment]
Hmm, this fixed itself at some point without me touching the code... Closing this issue.

**Comment by EzerArch** [comment]
> this fixed itself at some point without me touching the code

Because it was never broken, *probably* your Flight Control that was messed up or your armor was too heavy. I'm using the latest MPS build (0.11.0.175), my MPS jetpack is 3 or 4x faster than Mekanism jetpack.

**Comment by Korynkai** [comment]
Yeah, actually after some experimentation, I realized this was both to do with weight and flight control being set wrong. Indeed this was simply an instance issue and never an actual issue in the code.
