### ISSUE TITLE
Crash on Startup, potential problem with MinecraftLoadingScreen?

### ISSUE THREAD

**Issue by HyperMan19680** [QMXTech/MachineMusePowersuits#7]
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 12/11/14 12:12 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/machinemuse/powersuits/item/ItemPowerFist
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:502)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at com.creativemd.minecraftloader.ClientHelper.startGame(ClientHelper.java:260)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/machinemuse/powersuits/item/ItemPowerFist
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.ILanguageAdapter$ScalaAdapter.setInternalProxies(ILanguageAdapter.java:139)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:81)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.creativemd.minecraftloader.MinecraftDummyContainer.callMethod(MinecraftDummyContainer.java:209)
	at com.creativemd.minecraftloader.MinecraftDummyContainer.onModEvent(MinecraftDummyContainer.java:201)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	... 11 more
Caused by: java.lang.ClassNotFoundException: net.machinemuse.powersuits.item.ItemPowerFist
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 42 more
Caused by: java.lang.NoClassDefFoundError: net/machinemuse/api/OmniWrench
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 44 more
Caused by: java.lang.ClassNotFoundException: net.machinemuse.api.OmniWrench
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 48 more
Caused by: java.lang.NoClassDefFoundError: net/machinemuse/api/ModularCrowbar
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 50 more
Caused by: java.lang.ClassNotFoundException: net.machinemuse.api.ModularCrowbar
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 54 more
Caused by: java.lang.NoClassDefFoundError: mods/railcraft/api/core/items/IToolCrowbar
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 56 more
Caused by: java.lang.ClassNotFoundException: mods.railcraft.api.core.items.IToolCrowbar
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 60 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3906277048 bytes (3725 MB) / 4281597952 bytes (4083 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096M -Xms4096M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1240 Minecraft Forge 10.13.2.1240 155 mods loaded, 154 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.85.1240} [Forge Mod Loader] (forge-1.7.10-10.13.2.1240.jar) Unloaded->Constructed
	Forge{10.13.2.1240} [Minecraft Forge] (forge-1.7.10-10.13.2.1240.jar) Unloaded->Constructed
	Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed
	CazzarCoreLib{1.2.1-SNAPSHOT} [Cazzar Core Lib] (CazzarCoreLib-1.2.1-SNAPSHOT-universal.jar) Unloaded->Constructed
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed
	minecraftloader{0.1} [MinecraftLoader] (minecraft.jar) Unloaded->Constructed
	NotEnoughItems{1.0.3.67} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.67-universal.jar) Unloaded->Constructed
	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10-snapshot-135.jar) Unloaded->Constructed
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed
	backpacks16840{3.0.1} [Backpacks!] (zz-backpacks 1.7.10 - 3.0.2.jar) Unloaded->Constructed
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed
	malisiscore{1.7.10-0.10.2+unknown-b0.git-unknown} [Malisis Core] (malisiscore-1.7.10-0.10.2.jar) Unloaded->Constructed
	sapmanpack{2.1.0} [SanAndreasPs Manager Pack CORE edition] (minecraft.jar) Unloaded->Constructed
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed
	Thaumcraft{4.2.1.4} [Thaumcraft] (Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed
	arsmagica2{1.4.0.005} [Ars Magica 2] (1.7.10_AM2_1.4.0.005.jar) Unloaded->Constructed
	SC0_SpaceCore{0.7.12} [SpaceCore] ([1.7.10] SpaceCore 0.7.12.jar) Unloaded->Constructed
	MCP_Wheel{1.1.2} [MC+ Wheel] ([1.7.10][1.2] MC+ ModPack - v3.jar) Unloaded->Constructed
	MCP_Cart{1.3.0} [MC+ Cart] ([1.7.10][1.2] MC+ ModPack - v3.jar) Unloaded->Constructed
	MCP_Clippers{1.1.2} [MC+ Clippers] ([1.7.10][1.2] MC+ ModPack - v3.jar) Unloaded->Constructed
	MCP_FirePit{1.0.3} [MC+ FirePit] ([1.7.10][1.2] MC+ ModPack - v3.jar) Unloaded->Constructed
	MCP_Gems{1.2.1} [MC+ Gems] ([1.7.10][1.2] MC+ ModPack - v3.jar) Unloaded->Constructed
	MCP_Lock{1.2.2} [MC+ Lock] ([1.7.10][1.2] MC+ ModPack - v3.jar) Unloaded->Constructed
	MCP_Loom{1.2.3} [MC+ Loom] ([1.7.10][1.2] MC+ ModPack - v3.jar) Unloaded->Constructed
	MCP_Lumber{1.0.2} [MC+ Lumber] ([1.7.10][1.2] MC+ ModPack - v3.jar) Unloaded->Constructed
	MCP_Quartz{1.3.2} [MC+ Quartz] ([1.7.10][1.2] MC+ ModPack - v3.jar) Unloaded->Constructed
	MCP_Quiver{1.3.2} [MC+ Quiver] ([1.7.10][1.2] MC+ ModPack - v3.jar) Unloaded->Constructed
	MCP_Satchel{1.3.2} [MC+ Satchel] ([1.7.10][1.2] MC+ ModPack - v3.jar) Unloaded->Constructed
	MCP_Saw{1.0.1} [MC+ Saw] ([1.7.10][1.2] MC+ ModPack - v3.jar) Unloaded->Constructed
	MCP_Sickle{1.0.0} [MC+ Sickle] ([1.7.10][1.2] MC+ ModPack - v3.jar) Unloaded->Constructed
	MCP_TrappedLadder{1.1.2} [MC+ TrappedLadder] ([1.7.10][1.2] MC+ ModPack - v3.jar) Unloaded->Constructed
	MCP_Turtle{1.2.3} [MC+ Turtle] ([1.7.10][1.2] MC+ ModPack - v3.jar) Unloaded->Constructed
	MCP_Vines{1.0.1} [MC+ Vines] ([1.7.10][1.2] MC+ ModPack - v3.jar) Unloaded->Constructed
	DC1{3.4.2.19} [KingCore] ([1.7.2+] KingCore v3.4.2.19.jar) Unloaded->Constructed
	EB{2.1.2.6} [Ender Book] ([1.7.2] EnderBook v2.1.2.6.jar) Unloaded->Constructed
	abm{0.2} [Anime Battle Mod] (ABM 1.7.10 0.2.jar) Unloaded->Constructed
	satscapealarmcraft{1.0} [Alarmcraft] (Alarmcraft-1.0-(1.7.10).jar) Unloaded->Constructed
	AnimationAPI{1.2.3} [AnimationAPI] (AnimationAPI-1.7.10-1.2.3.jar) Unloaded->Constructed
	armourersWorkshop{1.7.10-0.22.2.37} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.22.2.37.jar) Unloaded->Constructed
	Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed
	CoFHCore{1.7.10R3.0.0B8} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B8-36.jar) Unloaded->Constructed
	asielib{0.3.3} [asielib] (AsieLib-1.7.10-0.3.3.jar) Unloaded->Constructed
	Waila{1.5.5} [Waila] (Waila-1.5.5_1.7.10.jar) Unloaded->Constructed
	Automagy{0.15} [Automagy] (Automagy-1.7.10-0.15.jar) Unloaded->Constructed
	AwesomeSauceCore{0.1.0} [AwesomeSauce Core] (AwesomeSauceCore-1.7.x-b40.jar) Unloaded->Constructed
	ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed
	AwesomeSauceComponents{0.1.0} [AwesomeSauce Components] (AwesomeSauceCore-1.7.x-b40.jar) Unloaded->Constructed
	balancedexchange{3.0.1} [Balanced Exchange] (balancedexchange 1.7.10 - 3.0.2.jar) Unloaded->Constructed
	bdlib{1.5.1.32} [BD Lib] (bdlib-mc1710-1.5.1.32.jar) Unloaded->Constructed
	BetterChests{1.1.1.8} [BetterChests] (BetterChests-1.7.10-1.1.1.8.jar) Unloaded->Constructed
	betterstorage{0.11.1.121} [BetterStorage] (BetterStorage-1.7.10-0.11.1.121.jar) Unloaded->Constructed
	BiblioCraft{1.9.1} [BiblioCraft] (BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed
	BuildCraft|Core{6.2.2} [BuildCraft] (buildcraft-6.2.2.jar) Unloaded->Constructed
	BuildCraft|Transport{6.2.2} [BC Transport] (buildcraft-6.2.2.jar) Unloaded->Constructed
	BuildCraft|Silicon{6.2.2} [BC Silicon] (buildcraft-6.2.2.jar) Unloaded->Constructed
	BuildCraft|Builders{6.2.2} [BC Builders] (buildcraft-6.2.2.jar) Unloaded->Constructed
	BuildCraft|Energy{6.2.2} [BC Energy] (buildcraft-6.2.2.jar) Unloaded->Constructed
	BuildCraft|Factory{6.2.2} [BC Factory] (buildcraft-6.2.2.jar) Unloaded->Constructed
	C9Light{0.7.2} [C9Light] (C9Light-0.7.2.jar) Unloaded->Constructed
	clockworkphase{1.7.10_1.0a} [Clockwork Phase] (clockworkphase-1.7.10_1.0a.jar) Unloaded->Constructed
	CMDfiles{0} [CMDfiles] (CMD files.jar) Unloaded->Constructed
	CompactMachines{1.7.10-1.13} [Compact Machines] (compactmachines-1.7.10-1.13.jar) Unloaded->Constructed
	cosmeticWings{0.4.2} [Cosmetic Wings] (Cosmetic-Wings-1.7.10-0.4.2.jar) Unloaded->Constructed
	CosmeticArmor{1.0.5} [Cosmetic Armor] (CosmeticArmor-1.7.10-1.0.5.B8-universal.jar) Unloaded->Constructed
	craftingpillars{1.5.5} [Crafting Pillars] (craftingpillars-1.7.10-1.5.8.jar) Unloaded->Constructed
	EasyCrafting{1.7.10-2.0.1.16} [Easy Crafting] (EasyCrafting-1.7.10-2.0.1.16.jar) Unloaded->Constructed
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed
	EnderIO{1.7.10-2.2.2.288} [Ender IO] (EnderIO-1.7.10-2.2.2.288.jar) Unloaded->Constructed
	EnderStorage{1.4.5.26} [EnderStorage] (EnderStorage-1.7.10-1.4.5.26-universal.jar) Unloaded->Constructed
	ThermalExpansion{1.7.10R4.0.0B6} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B6-16.jar) Unloaded->Constructed
	EnderTech{1.7.10-0.3.0.353} [EnderTech] (EnderTech-1.7.10-0.3.0.353.jar) Unloaded->Constructed
	enderutilities{0.3.5.1} [Ender Utilities] (enderutilities-1.7.10-0.3.5.1.jar) Unloaded->Constructed
	enhancedportals{3.0.9} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.9.jar) Unloaded->Constructed
	ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed
	ExtraUtilities{1.2.0} [Extra Utilities] (extrautilities-1.2.0.jar) Unloaded->Constructed
	fillchevsky{b3} [Fill Tool] (FillTool_1.7.2_b3.zip) Unloaded->Constructed
	ftfloocraft{1.7.10-1.2} [Floocraft] (Floocraft-1.7.10-1.2.jar) Unloaded->Constructed
	IC2{2.2.654-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.654-experimental.jar) Unloaded->Constructed
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-161.jar) Unloaded->Constructed
	ForbiddenMagic{1.7.10-0.55} [Forbidden Magic] (Forbidden Magic-1.7.10-0.55.jar) Unloaded->Constructed
	foxlib{1.7.10-0.6.0} [FoxLib] (FoxLib-1.7.10-0.6.0.jar) Unloaded->Constructed
	GalacticraftCore{3.0.6} [Galacticraft Core] (GalacticraftCore-1.7-3.0.6.232.jar) Unloaded->Constructed
	GalacticraftMars{3.0.6} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.6.232.jar) Unloaded->Constructed
	iChunUtil{4.1.2} [iChunUtil] (iChunUtil-4.1.2.jar) Unloaded->Constructed
	IGWMod{1.1.1-17} [In-Game wiki Mod] (IGW-Mod-1.7.10-1.1.1-17-universal.jar) Unloaded->Constructed
	ImmibisCore{59.0.4} [Immibis Core] (immibis-core-59.0.4.jar) Unloaded->Constructed
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed
	JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed
	LLadders{0.4.0} [Luppii's Ladders] (Ladders-0.4.0-MC1.7.10.jar) Unloaded->Constructed
	lmmx{1.0} [lmmx] (littleMaidMobX) Unloaded->Constructed
	MMMLibX{1.7.x-srg-1} [MMMLibX] (littleMaidMobX) Unloaded->Constructed
	MultiBench{1.7.2-x} [MultiBench] (littleMaidMobX) Unloaded->Constructed
	zabuton{1.0} [zabuton] (littleMaidMobX) Unloaded->Constructed
	LunatriusCore{1.1.2.18} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.18-universal.jar) Unloaded->Constructed
	malisisdoors{1.7.10-1.3.1} [Malisis' Doors] (malisisdoors-1.7.10-1.3.1.jar) Unloaded->Constructed
	minegicka3{1.0.0} [Minegicka III] (minegicka3-1.7.10-1.0.0.jar) Unloaded->Constructed
	MineMenu{1.2.0} [MineMenu] (MineMenu-1.7.10-1.2.0.B44-universal.jar) Unloaded->Constructed
	modularsystemsapi{0.0.1} [Modular Systems API] (Modular Systems-1.7.10-1.7.1.jar) Unloaded->Constructed
	modularsystems{1.7.1} [Modular Systems] (Modular Systems-1.7.10-1.7.1.jar) Unloaded->Constructed
	numina{0.4.0.100} [Numina] (Numina-0.4.0.100.jar) Unloaded->Constructed
	powersuits{0.11.0.4-QMX} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.4-QMX.jar) Unloaded
	MultiPageChest{1.3.3} [Multi Page Chest] (MultiPageChest-1.3.3-MC1.7.10.jar) Unloaded->Constructed
	MutantCreatures{1.4.7} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.7.jar) Unloaded->Constructed
	MyTownCore{2.0} [MyTownCore] (MyEssentials-Core-1.7.10-1.3-universal.jar) Unloaded->Constructed
	notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b29.jar) Unloaded->Constructed
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-268.jar) Unloaded->Constructed
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-511.jar) Unloaded->Constructed
	openmodularturrets{1.3.2} [Open Modular Turrets] (OpenModularTurrets-1.7.10-1.3.2-24.jar) Unloaded->Constructed
	PetBat{1.3.6} [Pet Bat] (PetBat-1.7.10.jar) Unloaded->Constructed
	PneumaticCraft{1.4.3-40} [PneumaticCraft] (PneumaticCraft-1.7.10-1.4.3-40-universal.jar) Unloaded->Constructed
	Railcraft{9.4.0.0} [Railcraft] (Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed
	PowerConverters{1.7.10-2.1} [Power Converters] (PowerConverters-1.7.10-2.1.jar) Unloaded->Constructed
	powersuitaddons{@VERSION@} [Modular Powersuits Addon] (PowersuitAddons-908-QMX.jar) Unloaded->Constructed
	quasarflame{ALPHA 1.0} [QuasarFlame_Develpment] (quasarflamev038222501.zip) Unloaded->Constructed
	quickhotbar{1.03} [Quick Hotbar] (quickhotbar_1710_1.03.jar) Unloaded->Constructed
	RandomThings{2.2.2} [Random Things] (RandomThings-2.2.2.jar) Unloaded->Constructed
	RedstoneArsenal{1.7.10R1.1.0RC1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar) Unloaded->Constructed
	simplyjetpacks{1.3.0} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.3.0.jar) Unloaded->Constructed
	ttCore{MC1.7.10-0.1.0-41} [ttCore] (ttCore-MC1.7.10-0.1.0-41.jar) Unloaded->Constructed
	RArm{1.1pre} [Redstone Armory] (RedstoneArmory-1.7.10-1.1-14-universal.jar) Unloaded->Constructed
	RefinedRelocation{1.0.6h} [Refined Relocation] (RefinedRelocation-1.7.10-1.0.6h.jar) Unloaded->Constructed
	RiskyKensUtilities{0.0.20} [Risky Ken's Utilities] (RiskyKensUtilities-1.7.10-0.0.21.jar) Unloaded->Constructed
	rivalrebels{1.7.10A} [Rival Rebels] (rivalrebels-1.7.10A.jar) Unloaded->Constructed
	RopesPlus{1.6.3} [Ropes+] (RopePlus-1.7.10.jar) Unloaded->Constructed
	Schematica{1.7.3.105} [Schematica] (Schematica-1.7.10-1.7.3.105-universal.jar) Unloaded->Constructed
	SlimevoidLib{2.0.4.6} [Slimevoid Library] (SlimevoidLibrary-2.0.4.6.jar) Unloaded->Constructed
	SwordPedestal{1.0(1.7.10)} [Sword Pedestal] (SwordPedestal-1.0(1.7.10).jar) Unloaded->Constructed
	Sync{4.0.0} [Sync] (Sync-4.0.0.jar) Unloaded->Constructed
	TallDoors{0.5.1} [Tall Doors Mod] (TallDoors-1.7.10-0.5.2.jar) Unloaded->Constructed
	WaslieCore{1.1} [WaslieCore] (WaslieCore-1.1_B43 (1).jar) Unloaded->Constructed
	ThaumcraftExtras{1.0} [Thaumcraft Extras 2] (ThaumcraftExtras-2-1.0_B52.jar) Unloaded->Constructed
	THKaguyaMod{2.83-1.7.10} [Itutu no Nandai MOD+ (Touhou Items Mod)] (THKaguya.zip) Unloaded->Constructed
	transportterminal{1.0b} [Transport Terminals] (Transport-Terminals-1.0b.jar) Unloaded->Constructed
	TravellersGear{1.10.1} [Traveller's Gear] (TravellersGear-1.7.10-1.10.1.jar) Unloaded->Constructed
	Tubestuff{59.0.1} [Tubestuff] (tubestuff-59.0.1.jar) Unloaded->Constructed
	UtilityMobs{3.1.1} [Utility Mobs] (UtilityMobs-1.7.10-3.1.1.jar) Unloaded->Constructed
	VersionChecker{1.1.7} [Version Checker] (VersionChecker-1.1.7.jar) Unloaded->Constructed
	WailaHarvestability{1.1.0} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded->Constructed
	wailaplugins{MC1.7.10-0.0.1-7} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.0.1-7.jar) Unloaded->Constructed
	wawla{1.0.9} [What Are We Looking At] (Wawla-1.0.9_1.7.10.jar) Unloaded->Constructed
	WirelessRedstoneCore{1.8.0.0} [Wireless Redstone] (WirelessRedstoneCore-1.8.0.0.jar) Unloaded->Constructed
	witchery{0.20.6} [Witchery] (witchery-1.7.10-0.20.6.jar) Unloaded->Constructed
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed
	zeldaswordskills{1.7.10-beta-0.1.7.1} [Zelda Sword Skills] (zeldaswordskills-1.7.10-beta-0.1.7.1.jar) Unloaded->Constructed
	zssaddon{1.7.10-alpha-0.0.1} [Zelda Sword Skills Addon] (zeldaswordskillsaddon-v0.0.3a.jar) Unloaded->Constructed
	McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed
	redgear_core{2.1.5} [Red Gear Core] (RedGearCore-1.7.10-2.1.5.jar) Unloaded->Constructed
	ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed
	asielibcore{} [AsieLib CoreMod] (minecraft.jar) Unloaded->Disabled
	OpenModsLib crash transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED],[map_gen_fix:ENABLED],[movement_callback:FINISHED],[stencil_patches:FINISHED]

Yeah, dunno what to say about this one. That's pretty much all I got.

**Comment by Korynkai** [comment]
This should be fixed in the current build.
